<?php

/**
 * BaseShippingTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $expected_date
 * @property integer $staff_id
 * @property string $destination
 * @property string $note
 * @property boolean $isactive
 * @property ShippingTransactionDetail $ShippingTransactioniDetail
 * @property Staff $Staff
 * 
 * @method integer                   getId()                         Returns the current record's "id" value
 * @method date                      getExpectedDate()               Returns the current record's "expected_date" value
 * @method integer                   getStaffId()                    Returns the current record's "staff_id" value
 * @method string                    getDestination()                Returns the current record's "destination" value
 * @method string                    getNote()                       Returns the current record's "note" value
 * @method boolean                   getIsactive()                   Returns the current record's "isactive" value
 * @method ShippingTransactionDetail getShippingTransactioniDetail() Returns the current record's "ShippingTransactioniDetail" value
 * @method Staff                     getStaff()                      Returns the current record's "Staff" value
 * @method ShippingTransaction       setId()                         Sets the current record's "id" value
 * @method ShippingTransaction       setExpectedDate()               Sets the current record's "expected_date" value
 * @method ShippingTransaction       setStaffId()                    Sets the current record's "staff_id" value
 * @method ShippingTransaction       setDestination()                Sets the current record's "destination" value
 * @method ShippingTransaction       setNote()                       Sets the current record's "note" value
 * @method ShippingTransaction       setIsactive()                   Sets the current record's "isactive" value
 * @method ShippingTransaction       setShippingTransactioniDetail() Sets the current record's "ShippingTransactioniDetail" value
 * @method ShippingTransaction       setStaff()                      Sets the current record's "Staff" value
 * 
 * @package    primal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShippingTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shipping_transaction');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('expected_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('staff_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('destination', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('note', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('isactive', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShippingTransactionDetail as ShippingTransactioniDetail', array(
             'local' => 'id',
             'foreign' => 'shipping_transaction_id',
             'onDelete' => 'cascade'));

        $this->hasOne('Staff', array(
             'local' => 'staff_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}