<?php

/**
 * ShippingTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    primal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShippingTransaction extends BaseShippingTransaction
{

    public static function getLateShipments() {

        return Doctrine_Query::create()
        ->from('ShippingTransaction s')
        ->where('s.expected_date <= CURRENT_TIMESTAMP()')
        ->execute(); 
    }

    public function __toString() {
        return $this->getDestination() . ' ' . $this->getDateTimeObject('created_at')->format('y-m-d_h:i');
    }
}
