<?php

/**
 * ShippingTransactionDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    primal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShippingTransactionDetail extends BaseShippingTransactionDetail
{

    public static function getByShippingTransactionId($shipping_transaction_id) {

        return Doctrine_Query::create()
        ->from('ShippingTransactionDetail s')
        ->where('s.shipping_transaction_id = ?',$shipping_transaction_id)
        ->orderBy('s.created_at DESC')
        ->execute();

    }

    public function getUser() {

      return $this->getShippingTransaction()->getStaff();

    }

    public function getDestination() {

      return $this->getShippingTransaction()->getDestination();

    }

    public function getIsactive() {
    
      return ($this->getShippingTransaction()->getIsactive())?"yes":"no";

    }

}
