<?php

/**
 * ShippingTransactionDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShippingTransactionDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShippingTransactionDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShippingTransactionDetail');
    }
}