<?php

/**
 * ShippingTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShippingTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShippingTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShippingTransaction');
    }
}