<?php

/**
 * Staff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    primal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Staff extends BaseStaff
{

    public static function loggedIn() {
      $currentUser = sfContext::getInstance()->getUser();

      $q = Doctrine_Query::create()
      ->select('s.id')
      ->from('Staff s')
      ->where('s.sf_guard_user_id = ?',$currentUser->getId())
      ->fetchOne()->id;

      return $q;
    }


    function __toString() {

        return $this->getUser()->getFirstName() . ' ' . $this->getUser()->getLastName();

    }


}
