generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Staff
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: User Management
        display: [user]        
      filter:  ~
      form:    ~
      edit:
        title: Modifying User '%%User%%'
      new:
        title: User Creation
